::JUEGO DE CARACTERES OEM850
@echo off
::PERMITE QUE SE ACTUALICEN LAS VARIABLES EN TIEMPO DE EJECUCI‡N EN EL BUCLE, LLAMAR CON !VARIABLE!
SETLOCAL ENABLEDELAYEDEXPANSION
set /A _num=0
for %%a in ("E:\V°deos\CURIOSAMENTE\CAPITALISMO O SOCIALISMO_64_56_288p_?.mp4") do (
	set _NOMBRE_COMPLETO_ARCHIVO=%%a
::	echo.%archivo:~0,58%_140s!archivo:~-6!
::	SE REDUCE LA DURACI‡N DEL VIDEO A 140 SEGUNDOS (TWITTER) Y SE RECODIF÷CA VIDEO 64KBPS AUDIO 56KBPS
	ffmpeg -i "%%a" -b:v 64k -b:a 56k -vf "setpts=0.877078*PTS" -af "atempo=1.140150" "%archivo:~0,58%_140s!archivo:~-6!"
	set /A _num += 1
)